In [1]:
from ML_Package.KNNClassifier import KNNClassifier


knn = KNNClassifier()

In [2]:
import numpy as np


# 特征
raw_data_x= [[3.393533211,2.331273381],
             [2.110073483,1.781539638],
             [1.343808831,3.368360954],
             [3.582294042,4.679179110],
             [2.280362439,2.866990263],
             [7.423436942,4.696522875],
             [5.745051997,3.533989803],
             [9.172168622,2.511101045],
             [7.792783481,3.424088941],
             [7.939820817,0.791637231]
            ]
# 所属类别
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

X_train = np.asarray(raw_data_x)
y_train = np.asarray(raw_data_y)
X_train, y_train

(array([[3.39353321, 2.33127338],
        [2.11007348, 1.78153964],
        [1.34380883, 3.36836095],
        [3.58229404, 4.67917911],
        [2.28036244, 2.86699026],
        [7.42343694, 4.69652288],
        [5.745052  , 3.5339898 ],
        [9.17216862, 2.51110105],
        [7.79278348, 3.42408894],
        [7.93982082, 0.79163723]]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]))

In [3]:
knn.fit(X_train, y_train)

KNNClassifier()

In [8]:
val_X = np.asarray([8.093607318,3.365731514])
val_X = val_X.reshape((1, -1))

In [9]:
knn.predict(val_X)

array([1])