In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
XDEMO = np.random.randint(1, 100, (5, 3))
XDEMO

array([[43, 76, 14],
       [78, 59, 19],
       [13, 51, 35],
       [23, 40, 84],
       [62, 42, 98]])

In [3]:
np.ones((len(XDEMO), 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [4]:
np.hstack([np.ones((len(XDEMO), 1)), XDEMO])

array([[ 1., 43., 76., 14.],
       [ 1., 78., 59., 19.],
       [ 1., 13., 51., 35.],
       [ 1., 23., 40., 84.],
       [ 1., 62., 42., 98.]])

In [5]:
boston = datasets.load_boston()
X = boston.data
y = boston.target
X = X[y < 50.0]
y = y[y < 50.0]

X, y

(array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 1

In [6]:
from ML_Package.train_test_split import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [8]:
X_train.shape

(392, 13)

In [9]:
from ML_Package.MultivarateRegression import MultivarateRegression

In [10]:
mr = MultivarateRegression()

In [11]:
mr.fit_normal(X_train, y_train)

MultivarateRegression()

In [12]:
mr.coff_

array([-1.29086635e-01,  3.32531244e-02, -2.75753039e-02,  7.86564379e-01,
       -1.24277188e+01,  3.70458413e+00, -2.73338250e-02, -1.16492896e+00,
        2.75767059e-01, -1.28516014e-02, -8.64549986e-01,  9.87219150e-03,
       -3.44628031e-01])

In [13]:
mr.score(X_test, y_test)

0.7898886436694377

In [14]:
np.argsort(mr.coff_)

array([ 4,  7, 10, 12,  0,  2,  6,  9, 11,  1,  8,  3,  5])

In [15]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')